# Generated by Django 6.0.3 on 2026-03-27 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_file', models.FileField(upload_to='encrypted/')),
                ('original_name', models.CharField(max_length=255)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('encryption_key_digest', models.CharField(max_length=64)),
                ('key_salt', models.CharField(max_length=64)),
                ('fermat_base', models.PositiveBigIntegerField(default=0)),
                ('fermat_modulus', models.PositiveBigIntegerField(default=0)),
                ('fermat_result', models.PositiveBigIntegerField(default=0)),
                ('aes_nonce', models.CharField(max_length=64)),
                ('aes_tag', models.CharField(max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('download_limit', models.PositiveIntegerField(default=1)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('login', 'Login'), ('share', 'Share'), ('view', 'View'), ('profile_update', 'Profile Update')], max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('file_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.securefile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
