# Generated by Django 6.0.3 on 2026-03-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View only'), ('view_download', 'View and download')], default='view', max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('secure_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_entries', to='storage.securefile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_access_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'unique_together': {('secure_file', 'viewer')},
            },
        ),
    ]
